### ISSUE TITLE
Incompatible with sidekiq >= 6.4.2

### ISSUE THREAD

**Issue by rusterholz** [ezcater/sidekiq_publisher#55]
Between v6.4.1 and v6.4.2, the `process_single` method was [removed](https://github.com/mperham/sidekiq/compare/v6.4.1...v6.4.2) from Sidekiq::Client. This breaks the SidekiqPublisher::Client's `bulk_push` method, which means no jobs get published.

See also https://github.com/mperham/sidekiq/issues/5311

A fix (https://github.com/mperham/sidekiq/pull/5312) for https://github.com/mperham/sidekiq/issues/5311 will be in sidekiq v6.5.0, but that fix does not fix our bug aswe are using a private method which was eliminated during refactoring).

**Comment by rusterholz** [comment]
A JIRA ticket to fix this issue was added to our team's board here: https://ezcater.atlassian.net/browse/WF-264

**Comment by jmpage** [comment]
@violet-graves let's do it. Would you like to make the PR?

**Comment by violet-graves** [comment]
[sure !](https://github.com/ezcater/sidekiq_publisher/pull/59)
